export const abiaStateMDAs = [
  "Ministry of Agriculture",
  "Ministry of Basic Education",
  "Ministry of Tertiary Education",
  "Ministry of Health",
  "Ministry of Environment",
  "Ministry of Finance",
  "Ministry of Budget & Planning",
  "Ministry of Justice",
  "Ministry of Works",
  "Ministry of Transport",
  "Ministry of Power & Public Utilities",
  "Ministry of Lands & Housing",
  "Ministry of Trade, Commerce & Industry",
  "Ministry of Science, Technology & Innovation",
  "Ministry of Industry and SMEs",
  "Ministry of Women Affairs",
  "Ministry of Youths & Sports Development",
  "Ministry of Information and Culture",
  "Ministry of Local Government & Chieftaincy Affairs",
  "Ministry of Labour & Productivity",
  "Ministry of Petroleum and Mineral Resources",
  "Ministry of Arts, Culture & Creative Economy",
  "Ministry of Homeland Security",

  "Abia State Universal Basic Education Board (ASUBEB)",
  "Abia State Primary Healthcare Development Agency",
  "Abia State Environmental Protection Agency (ASEPA)",
  "Abia State Sports Council",
  "Abia State Broadcasting Corporation (BCA)",
  "Abia GIS",
  "Abia State Local Government Service Commission",
  "Abia State Hospitals Management Board",
  "Abia State Law Reform Commission",
  "Abia State Tourism Board",
  "Abia State Emergency Management Agency",
  "Abia State Health Insurance Agency",
  "Abia State Road Maintenance Agency (ABROMA)",
  "Abia State Signage & Advertisement Agency (ABSSAA)",
  "Abia State Scholarship Board",
  "Abia State Library Board",
  "Abia State Water and Sewerage Corporation",
  "Abia State Board of Internal Revenue",
  "Abia State Independent Electoral Commission (ABSIEC)",
  "Abia State Oil Producing Areas Development Commission (ASOPADEC)",
  "Abia State Diaspora Commission",
  "Abia State Disability Commission",
  "Abia State Gaming and Control Board",
  "Abia State Orientation Agency",
  "Abia State Printing & Publishing Corporation",
  "Abia State Rural Water Sanitation Agency",
  "Abia State Fire Service",
  "Secondary Education Management Board (SEMB)",
  "Civil Service Commission",
  "Judicial Service Commission",

  "Abia State University (ABSU)",
  "Abia State Polytechnic, Aba",
  "College of Education (Technical), Arochukwu",
  "Abia State University Teaching Hospital (ABSUTH)",
  "Abia State Specialist Hospital & Diagnostic Centre",

  "Office of the Governor",
  "Office of the Deputy Governor",
  "Office of the Head of Service",
  "Office of the Accountant-General",
  "Office of the Auditor-General",
  "Office of the Secretary to the State Government",
  "Bureau of Political Affairs",
  "Bureau of Statistics",
  "Bureau of Public Procurement (Due Process)",
  "Bureau of Establishments and Pensions",
  "Bureau of Economic Affairs",
  "Bureau of Training",

  "Abia Transport Corporation (Abia Line Network)",
  "Abia State Housing & Property Corporation",
  "Abia Agricultural Development Programme (AADP)",
  "Umuahia Capital Development Authority (UCDA)",
  "Greater Aba Development Authority",
  "Abia Tourism Corporation",
  "Enyimba Football Club",
  "Abia Warriors Football Club",
  "Abia Cashew Corporation",
  "Abia Rubber Corporation",
  "Abia Palm-Friel Nigeria Ltd.",
] as const;
